# path: azure-aks-bitcoin-information/aks-manual-deployment/serviceA-deployment.yaml
# https://codefresh.io/learn/kubernetes-deployment/kubernetes-deployment-yaml/
#kube deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
        - name: service-a
          image: bitcoinregistry.azurecr.io/service-a:latest
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

---
#https://matthewpalmer.net/kubernetes-app-developer/articles/service-kubernetes-example-tutorial.html
#kube service
apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  type: ClusterIP
  selector:
    app: service-a
  ports:
    - name: http
      port: 5000
      targetPort: 5000
