#path: azure-aks-bitcoin-information\my-helm-chart\templates\serviceB-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.serviceB.name}}
  labels:
    app: {{ .Values.service.serviceB.name}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service.serviceB.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.service.serviceB.name}}
    spec:
      containers:
        - name: {{ .Values.service.serviceB.name}}
          image: {{ .Values.image.serviceB}}
          ports:
            - containerPort: {{ .Values.service.serviceB.port}}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.serviceB.port}}
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.serviceB.port}}
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceB.name}}
spec:
  type: {{ .Values.service.serviceB.type}}
  selector:
    app: {{ .Values.service.serviceB.name}}
  ports:
    - name: http
      port: {{ .Values.service.serviceB.port}}
      targetPort: {{ .Values.service.serviceB.port}}
